CREATE DATABASE QLKD_DONGHO
GO
USE QLKD_DONGHO
GO
CREATE TABLE HANG_SX
(
	ID				INT					IDENTITY(1,1),
	TEN				NVARCHAR(30)		NOT NULL,
	LOGO			VARCHAR(300)		NOT NULL,
	GIOITHIEU		NVARCHAR(500)			NULL,
	PRIMARY KEY(ID)
)
GO
CREATE TABLE DONG_HO
(
	ID				INT					IDENTITY(1,1),
	TEN				NVARCHAR(100)		NOT NULL,
	MAUMA			VARCHAR(20)			NOT NULL,
	KIEUMAY			NVARCHAR(30)		NOT NULL,
	KICHCO			FLOAT					NULL,
	DODAY			FLOAT					NULL,
	CHATLIEU_VO		NVARCHAR(30)			NULL,
	CHATLIEU_DAY	NVARCHAR(30)			NULL,
	CHATLIEU_KINH	NVARCHAR(30)			NULL,
	DOCHIEUNUOC		INT						NULL,
	BAOHANH			NVARCHAR(20)			NULL,						
	DONGIA			FLOAT				NOT NULL,
	KHUYENMAI		INT						NULL,
	ID_HANGSX		INT					NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID_HANGSX) REFERENCES HANG_SX(ID)
)
GO
CREATE TABLE HINH_ANH
(
	ID				INT					IDENTITY(1,1),
	URL				VARCHAR(500)		NOT NULL,
	ID_DONGHO		INT					NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID_DONGHO) REFERENCES DONG_HO(ID)
)
GO
CREATE TABLE KHACH_HANG
(
	ID				INT					IDENTITY(1,1),
	HOTEN			NVARCHAR(50)		NOT NULL,	
	NGAYSINH		DATE					NULL,
	DIACHI			NVARCHAR(100)			NULL,
	SDT				VARCHAR(10)			NOT NULL,
	EMAIL			VARCHAR(100)			NULL,
	PASS			VARCHAR(50)				NULL,
	PRIMARY KEY(ID)
)
GO
CREATE TABLE LUOT_LIKE
(
	ID				INT					IDENTITY(1,1),
	ID_KHACHHANG	INT					NOT NULL,
	ID_DONGHO		INT					NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID_KHACHHANG) REFERENCES KHACH_HANG(ID),
	FOREIGN KEY(ID_DONGHO) REFERENCES DONG_HO(ID)
)
GO
CREATE TABLE DON_HANG
(
	ID				INT					IDENTITY(1,1),
	ID_KHACHHANG	INT						NULL,
	HOTEN			NVARCHAR(50)		NOT NULL,
	DIACHI			NVARCHAR(100)			NULL,
	SDT				VARCHAR(10)			NOT NULL,
	EMAIL			VARCHAR(100)			NULL,
	TONGTIEN		FLOAT				NOT NULL,
	GHICHU			TEXT					NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID_KHACHHANG) REFERENCES KHACH_HANG(ID)
)
GO
CREATE TABLE DAT_HANG
(
	ID				INT					IDENTITY(1,1),
	ID_DONGHO		INT					NOT NULL,
	ID_DONHANG		INT					NOT NULL,
	SOLUONG			SMALLINT			NOT NULL,
	DONGIA			FLOAT				NOT NULL,
	GIAGIAM			FLOAT				NOT NULL,
	THANHTIEN		FLOAT				NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID_DONGHO) REFERENCES DONG_HO(ID),
	FOREIGN KEY(ID_DONHANG) REFERENCES DON_HANG(ID)
)
GO
CREATE TABLE NGUOI_DUNG
(
	ID				INT					IDENTITY(1,1),
	NAME			VARCHAR(30)			NOT NULL,
	PASS			VARCHAR(50)			NOT NULL,
	HOTEN			NVARCHAR(50)		NOT NULL,
	NGAYSINH		DATE					NULL,
	DIACHI			NVARCHAR(100)			NULL,
	SDT				VARCHAR(10)			NOT NULL,
	IS_SUPER_USER	BIT					NOT NULL,
	PRIMARY KEY(ID)
)
GO
CREATE TABLE QUYEN_LOI
(
	ID				INT					IDENTITY(1,1),
	LOAIHINH		VARCHAR(30)			NOT NULL,
	NOIDUNG			NVARCHAR(100)			NULL,
	PRIMARY KEY(ID)
)
GO
CREATE TABLE PHAN_QUYEN
(
	ID				INT					IDENTITY(1,1),
	ID_NGUOIDUNG	INT					NOT NULL,
	ID_QUYENLOI		INT					NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID_NGUOIDUNG) REFERENCES NGUOI_DUNG(ID),
	FOREIGN KEY(ID_QUYENLOI) REFERENCES QUYEN_LOI(ID)
)

