CREATE DATABASE QLKD_DONGHO
GO
USE QLKD_DONGHO
GO
CREATE TABLE DONG_HO
(
	ID				INT					IDENTITY(1,1),
	TEN				NVARCHAR(100)		NOT NULL,
	MAUMA			VARCHAR(20)			NOT NULL,
	KIEUMAY			NVARCHAR(30)		NOT NULL,
	KICHCO			FLOAT					NULL,
	DODAY			FLOAT					NULL,
	CHATLIEU_VO		NVARCHAR(30)			NULL,
	CHATLIEU_DAY	NVARCHAR(30)			NULL,
	CHATLIEU_KINH	NVARCHAR(30)			NULL,
	DOCHIEUNUOC		INT						NULL,
	BAOHANH			NVARCHAR(20)			NULL,						
	DONGIA			FLOAT				NOT NULL,
	KHUYENMAI		INT						NULL,
	PRIMARY KEY(ID)
)
GO
CREATE TABLE KHACH_HANG
(
	ID				INT					IDENTITY(1,1),
	HO				NVARCHAR(50)		NOT NULL,
	TEN				NVARCHAR(20)		NOT NULL,	
	NGAYSINH		DATE					NULL,
	DIACHI			NVARCHAR(100)			NULL,
	SDT				VARCHAR(10)			NOT NULL,
	EMAIL			VARCHAR(100)			NULL,
	PASS			VARCHAR(50)				NULL,
	PRIMARY KEY(ID)
)
GO
CREATE TABLE LUOT_LIKE
(
	ID				INT					IDENTITY(1,1),

)